<?php

namespace Base\BledvoyageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdminCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminCommentRepository extends EntityRepository
{
}
