<?php

namespace Base\BledvoyageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieTicketRepository extends EntityRepository
{
}
