<?php

namespace Base\BledvoyageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DateSortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateSortieRepository extends EntityRepository
{
    /*
    public function getDateDebut($id)
    {
        $qb = $this->createQueryBuilder('a')
                   ->where('a.annuler = :annuler AND a.sortie= :id')
                   ->setParameters(array(
                       'annuler'    => '0',
                       'id'         => $id,
                   ));
        return $qb;
    }
    */
}
