<?php

namespace Base\BledvoyageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OperateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperateurRepository extends EntityRepository
{
}
