<?php

namespace Base\BledvoyageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Sortie_sortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sortie_sortieRepository extends EntityRepository
{
}
